package protoc

import (
	"github.com/iancoleman/strcase"
	"google.golang.org/protobuf/compiler/protogen"
)

func getInterfaceName(message *protogen.Message) string {
	return strcase.ToLowerCamel(string(message.Desc.Parent().FullName())) + message.GoIdent.GoName + "Int" + structSuffix
}

func getStructName(message *protogen.Message) string {
	return strcase.ToLowerCamel(string(message.Desc.Parent().FullName())) + message.GoIdent.GoName + structSuffix
}

func getStructNewFunction(message *protogen.Message) string {
	return "new" + strcase.ToCamel(getStructName(message))
}

func getFilePath(f *protogen.File) string {
	return f.GeneratedFilenamePrefix + generatedExtension
}

func getFileHeaderComment(protoFile string) string {
	return "// Code generated by protoc-gen-fieldmask. DO NOT EDIT.\n" +
		"// source: " + protoFile
}

func getMessageName(message *protogen.Message) string {
	return strcase.ToSnake(message.GoIdent.GoName)
}
