package typescript

import (
	"github.com/iancoleman/strcase"
	"google.golang.org/protobuf/compiler/protogen"
)

func getPublicClassName(message *protogen.Message) string {
	return message.GoIdent.GoName + classSuffix
}

func getPrivateClassName(message *protogen.Message) string {
	return strcase.ToLowerCamel(string(message.Desc.Parent().FullName())) + message.GoIdent.GoName + classSuffix
}

func getFilePath(f *protogen.File) string {
	return f.GeneratedFilenamePrefix + generatedExtension
}

func getFileHeaderComment(protoFile string) string {
	return "// Code generated by protoc-gen-fieldmask. DO NOT EDIT.\n" +
		"// source: " + protoFile
}

func getMessageName(message *protogen.Message) string {
	return strcase.ToSnake(message.GoIdent.GoName)
}
